# Generated by Django 4.2.23 on 2025-12-23 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(choices=[('binance', 'Binance'), ('bybit', 'Bybit'), ('kucoin', 'KuCoin'), ('ftx', 'FTX'), ('kraken', 'Kraken'), ('coinbase', 'Coinbase Pro'), ('huobi', 'Huobi'), ('okx', 'OKX'), ('gateio', 'Gate.io'), ('bitfinex', 'Bitfinex'), ('poloniex', 'Poloniex'), ('bittrex', 'Bittrex'), ('bitstamp', 'Bitstamp')], default='binance', max_length=20)),
                ('api_key', encrypted_model_fields.fields.EncryptedTextField()),
                ('api_secret', encrypted_model_fields.fields.EncryptedTextField()),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], default='medium', max_length=10)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'exchange')},
            },
        ),
    ]
