# Generated by Django 4.2.23 on 2025-12-27 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auxobot', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='botconfig',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='instrument',
            field=models.CharField(choices=[('SOLUSDT', 'SOLUSDT (High Volatility)'), ('DOGEUSDT', 'DOGEUSDT (Meme Coin)'), ('ETHUSDT', 'ETHUSDT'), ('BTCUSDT', 'BTCUSDT'), ('BNBUSDT', 'BNBUSDT'), ('ADAUSDT', 'ADAUSDT'), ('XRPUSDT', 'XRPUSDT'), ('PEPEUSDT', 'PEPEUSDT (Extreme Volatility)'), ('1000SHIBUSDT', '1000SHIBUSDT')], default='SOLUSDT', help_text='Select the perpetual futures pair for grid trading', max_length=20),
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='exchange',
            field=models.CharField(choices=[('binance', 'Binance'), ('bybit', 'Bybit'), ('kucoin', 'KuCoin'), ('okx', 'OKX'), ('gateio', 'Gate.io'), ('ftx', 'FTX'), ('kraken', 'Kraken'), ('coinbase', 'Coinbase Pro'), ('huobi', 'Huobi'), ('bitfinex', 'Bitfinex'), ('poloniex', 'Poloniex'), ('bittrex', 'Bittrex'), ('bitstamp', 'Bitstamp')], default='binance', max_length=20),
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_bot_configs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='botconfig',
            unique_together={('user', 'exchange', 'instrument')},
        ),
        migrations.CreateModel(
            name='DemoBotConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(choices=[('binance', 'Binance'), ('bybit', 'Bybit'), ('kucoin', 'KuCoin'), ('okx', 'OKX'), ('gateio', 'Gate.io'), ('ftx', 'FTX'), ('kraken', 'Kraken'), ('coinbase', 'Coinbase Pro'), ('huobi', 'Huobi'), ('bitfinex', 'Bitfinex'), ('poloniex', 'Poloniex'), ('bittrex', 'Bittrex'), ('bitstamp', 'Bitstamp')], default='binance', max_length=20)),
                ('api_key', encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('api_secret', encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('demo_api_key', encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('demo_api_secret', encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('instrument', models.CharField(choices=[('SOLUSDT', 'SOLUSDT (High Volatility)'), ('DOGEUSDT', 'DOGEUSDT (Meme Coin)'), ('ETHUSDT', 'ETHUSDT'), ('BTCUSDT', 'BTCUSDT'), ('BNBUSDT', 'BNBUSDT'), ('ADAUSDT', 'ADAUSDT'), ('XRPUSDT', 'XRPUSDT'), ('PEPEUSDT', 'PEPEUSDT (Extreme Volatility)'), ('1000SHIBUSDT', '1000SHIBUSDT')], default='SOLUSDT', max_length=20)),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], default='medium', max_length=10)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demo_bot_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
