# Generated by Django 4.2.23 on 2025-12-27 14:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxobot', '0002_alter_botconfig_unique_together_botconfig_instrument_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demobotconfig',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='demobotconfig',
            name='api_secret',
        ),
        migrations.AddField(
            model_name='botconfig',
            name='realized_pnl',
            field=models.DecimalField(decimal_places=8, default=Decimal('0E-8'), help_text='Realized PnL from closed trades', max_digits=18),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='total_pnl',
            field=models.DecimalField(decimal_places=8, default=Decimal('0E-8'), help_text='Total realized + unrealized PnL in USDT', max_digits=18),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='total_trades',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='unrealized_pnl',
            field=models.DecimalField(decimal_places=8, default=Decimal('0E-8'), help_text='Unrealized PnL from open positions', max_digits=18),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='win_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Win rate percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='demobotconfig',
            name='realized_pnl',
            field=models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=18),
        ),
        migrations.AddField(
            model_name='demobotconfig',
            name='total_pnl',
            field=models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=18),
        ),
        migrations.AddField(
            model_name='demobotconfig',
            name='total_trades',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='demobotconfig',
            name='unrealized_pnl',
            field=models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=18),
        ),
        migrations.AddField(
            model_name='demobotconfig',
            name='win_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
    ]
