# Generated by Django 4.2.23 on 2025-12-27 19:54

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auxobot', '0003_remove_demobotconfig_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfig',
            name='custom_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Custom order quantity per grid level (overrides risk default)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='demobotconfig',
            name='custom_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Custom order quantity per grid level (overrides risk default)', max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='ExtraConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_sol', models.DecimalField(decimal_places=2, default=Decimal('130.00'), max_digits=12, verbose_name='SOLUSDT Approx Price')),
                ('price_doge', models.DecimalField(decimal_places=6, default=Decimal('0.150000'), max_digits=12, verbose_name='DOGEUSDT Approx Price')),
                ('price_eth', models.DecimalField(decimal_places=2, default=Decimal('3400.00'), max_digits=12, verbose_name='ETHUSDT Approx Price')),
                ('price_btc', models.DecimalField(decimal_places=2, default=Decimal('68000.00'), max_digits=12, verbose_name='BTCUSDT Approx Price')),
                ('price_bnb', models.DecimalField(decimal_places=2, default=Decimal('600.00'), max_digits=12, verbose_name='BNBUSDT Approx Price')),
                ('price_ada', models.DecimalField(decimal_places=4, default=Decimal('0.6000'), max_digits=12, verbose_name='ADAUSDT Approx Price')),
                ('price_xrp', models.DecimalField(decimal_places=4, default=Decimal('0.6500'), max_digits=12, verbose_name='XRPUSDT Approx Price')),
                ('price_pepe', models.DecimalField(decimal_places=8, default=Decimal('0.00001200'), max_digits=12, verbose_name='PEPEUSDT Approx Price')),
                ('price_shib', models.DecimalField(decimal_places=8, default=Decimal('0.00002500'), max_digits=12, verbose_name='1000SHIBUSDT Approx Price')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extra_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Extra Configuration',
                'verbose_name_plural': 'Extra Configurations',
            },
        ),
    ]
