# Generated by Django 4.2.23 on 2025-12-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxobot', '0004_botconfig_custom_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfig',
            name='side',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='demobotconfig',
            name='side',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
