# Generated by Django 4.2.23 on 2025-12-29 02:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxobot', '0007_demobotlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='demobotconfig',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=20),
        ),
    ]
