# Generated by Django 4.2.23 on 2026-01-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxobot', '0008_demobotconfig_wallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='demobotconfig',
            name='high_risk_accepted',
            field=models.BooleanField(default=False, help_text='User has confirmed high risk for small accounts (<$200)'),
        ),
    ]
