# Generated by Django 4.2.23 on 2026-01-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxobot', '0009_demobotconfig_high_risk_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botconfig',
            name='risk_level',
            field=models.CharField(blank=True, choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], default='medium', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='demobotconfig',
            name='risk_level',
            field=models.CharField(blank=True, choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], default='medium', max_length=10, null=True),
        ),
    ]
